### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tadatuta** [godfreyd/bem-in-dynamic#2]
* [x] учитывать тоглы
* [x] оптимизировать logo.svg
* [x] уметь строить произвольные пути к статике
* [x] подписываться на скролл
